name: content_suppliers_rust
description: "Content Suppliers RUST bindings"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: "3.32.6"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.10.0
  plugin_platform_interface: ^2.0.2
  content_suppliers_api:
    path: ../content_suppliers_api
  freezed_annotation: ^3.1.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner: 
  freezed: ^3.2.3
  test: ^1.25.0
