name: content_suppliers_api
description: "Content Suppliers API"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: "3.32.6"

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints:
  build_runner:
  json_serializable: ^6.11.3
